=== conmaol/lexicopia_old/gd/lexeme.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>

<!--
  <xs:element name="lexicon">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="lexeme"/>
          <xs:element ref="ainmear_fireann"/>
          <xs:element ref="ainmear_boireann"/>
          <xs:element ref="ainmear"/>
          <xs:element ref="ainmear_fillte"/>
          <xs:element ref="iar-leasachan"/>
          <xs:element ref="buadhair"/>
          <xs:element ref="gnìomhair"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  -->

  <xs:element name="lexeme" type="lexeme-content"/>
  
  <xs:element name="ainmear_fireann" type="lexeme-content"/>

  <xs:element name="ainmear_boireann" type="lexeme-content"/>
  
  <xs:element name="ainmear" type="lexeme-content"/>
  
  <xs:element name="ainmear_fillte" type="lexeme-content"/>

  <xs:element name="iar-leasachan" type="lexeme-content"/>
  
  <xs:element name="buadhair" type="lexeme-content"/>
  
  <xs:element name="gnìomhair" type="lexeme-content"/>

  <xs:complexType name="lexeme-content">
    <xs:sequence>
      <xs:element ref="part" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="form" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="trans" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="note" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:element name="part">
    <xs:complexType>
      <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="form">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="orth" type="xs:token" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="trans">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:token">
          <xs:attribute name="index">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="no"/>
                <xs:enumeration value="only"/>
                <xs:enumeration value="yes"/>
                <!-- a few lexical forms need this -->
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== conmaol/lexicopia_old/gd/lexemes/loch.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="loch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>loch</orth>
    </form>
    <form>
      <orth>locha</orth>
    </form>
    <form>
      <orth>lochan</orth>
    </form>
    <trans>lake</trans>
    <trans>loch</trans>
    <note>Listed in An Seotal: Geography.</note>
  </lexeme>

=== conmaol/lexicopia_old/gd/lexemes/turas.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="turas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>turas</orth>
    </form>
    <form>
      <orth>turais</orth>
    </form>
    <form>
      <orth>tursan</orth>
    </form>
    <trans>trip</trans>
    <trans>excursion</trans>
    <trans>expedition</trans>
    <trans>journey</trans>
    <trans>passage</trans>
    <trans>tour</trans>
    <trans>occasion</trans>
    <trans>time</trans>
  </lexeme>

=== conmaol/lexicopia_old/gd/lexemes/iolaire_bhuidhe.xml
<?xml version="1.0" encoding="UTF-8"?>

<ainmear_boireann id="iolaire_bhuidhe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>iolaire bhuidhe</orth>
    </form>
    <trans>golden eagle</trans>
    <trans>Aquila chrysaetos</trans>
    <note>From Scottish Natural Heritage's Faclan NÃ dair.</note>
    <note>Info: There are 276 Gaelic place-names in Scotland which name the iolaire 'eagle'. Over two-thirds are thought to represent the golden eagle and the remainder the white-tailed sea
      eagle.</note>
    <note>Audio: http://www.snh.org.uk/gaidhlig/audio/iolaire-bhuidhe.mp3</note>
    <note>Listed in CM.</note>
  </ainmear_boireann>

=== conmaol/lexicopia_old/gd/lexemes/duilleag.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="duilleag" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <part ref="_ag-suffix"/>
    <form>
      <orth>duilleag</orth>
    </form>
    <trans>leaf</trans>
    <trans>page</trans>
    <note>Listed in An Seotal: Computing, as 'page'.</note>
    <note>page - duilleig(e) poss cpages - duilleagan pl</note>
  </lexeme>

=== conmaol/lexicopia_old/gd/lexemes/cràbhach.xml
<?xml version="1.0" encoding="UTF-8"?>

<buadhair id="cràbhach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>cràbhach</orth>
    </form>
    <trans>religious</trans>
    <trans>pious</trans>
    <trans>sactimonious</trans>
    <trans>pietistic</trans>
    <trans>pharisaic</trans>
    <note>Listed in An Seotal: Religious and Moral.</note>
    <note>Adjective. Derived from Old Irish 'cráibdech', and hence probably simplified from older 'crabhadhach'.</note>
  </buadhair>

=== conmaol/lexicopia_old/gd/lexemes/leumadair_bàn-ghobach.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="leumadair_bàn-ghobach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>leumadair bàn-ghobach</orth>
    </form>
    <trans>white-beaked dolphin</trans>
    <note>From Scottish Natural Heritage's Faclan Nàdair.</note>
    <note>Synonyms: deilf gheal-ghobach f</note>
    <note>Plurals: leumadairean bàn-ghobach, deilf gheal-ghobach</note>
    <note>Latin: Lagenorhynchus albirostris</note>
  </lexeme>

=== conmaol/lexicopia_old/gd/lexemes/prionnsapal.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="prionnsapal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>prionnsapal</orth>
    </form>
    <trans>principal</trans>
    <trans>principle</trans>
    <note>Listed in An Seotal: General.</note>
    <note>principal - prionnsapail poss cprincipals - prionnsapail plprincipals - prionnsapalan pl</note>
    <note>principle - prionnsapail poss cprinciples - prionnsapalan pl</note>
  </lexeme>

=== conmaol/lexicopia_old/gd/lexemes/teaghlach.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="teaghlach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>teaghlach</orth>
    </form>
    <form>
      <orth>teaghlaich</orth>
    </form>
    <form>
      <orth>teaghlaichean</orth>
    </form>
    <trans>family</trans>
    <trans>household</trans>
    <note>Listed in An Seotal: General, as 'family'.</note>
  </lexeme>
