=== conmaol/lexicopia_old/gd/lexeme.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>

<!--
  <xs:element name="lexicon">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="lexeme"/>
          <xs:element ref="ainmear_fireann"/>
          <xs:element ref="ainmear_boireann"/>
          <xs:element ref="ainmear"/>
          <xs:element ref="ainmear_fillte"/>
          <xs:element ref="iar-leasachan"/>
          <xs:element ref="buadhair"/>
          <xs:element ref="gnìomhair"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  -->

  <xs:element name="lexeme" type="lexeme-content"/>
  
  <xs:element name="ainmear_fireann" type="lexeme-content"/>

  <xs:element name="ainmear_boireann" type="lexeme-content"/>
  
  <xs:element name="ainmear" type="lexeme-content"/>
  
  <xs:element name="ainmear_fillte" type="lexeme-content"/>

  <xs:element name="iar-leasachan" type="lexeme-content"/>
  
  <xs:element name="buadhair" type="lexeme-content"/>
  
  <xs:element name="gnìomhair" type="lexeme-content"/>

  <xs:complexType name="lexeme-content">
    <xs:sequence>
      <xs:element ref="part" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="form" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="trans" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="note" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:element name="part">
    <xs:complexType>
      <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="form">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="orth" type="xs:token" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="trans">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:token">
          <xs:attribute name="index">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="no"/>
                <xs:enumeration value="only"/>
                <xs:enumeration value="yes"/>
                <!-- a few lexical forms need this -->
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== conmaol/lexicopia_old/gd/lexemes/cuideachd-noun.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="cuideachd-noun" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>cuideachd</orth>
    </form>
    <trans>company</trans>
    <trans>party</trans>
    <trans>troop</trans>
    <trans>body</trans>
    <trans>society</trans>
    <trans>train</trans>
  </lexeme>

=== conmaol/lexicopia_old/gd/lexemes/lagh.xml
<?xml version="1.0" encoding="UTF-8"?>

<ainmear_fireann id="lagh" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
    <form>
      <orth>lagh</orth>
    </form>
    <trans>law</trans>
    <note>Listed in An Seotal: General.</note>
    <note>law - lagha poss c laws - laghannan pl</note>
    <note>Listed in TYGD.</note>
    <note>Listed in CM.</note>
  </ainmear_fireann>

=== conmaol/lexicopia_old/gd/lexemes/craobh_fheòir.xml
<?xml version="1.0" encoding="UTF-8"?>

<lexeme id="craobh_fheòir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lexeme.xsd">
  <part ref="craobh"/>
  <part ref="feur"/>
  <form>
    <orth>craobh fheòir</orth>
  </form>
  <trans>grass tree</trans>
  <trans>lancewood</trans>
  <trans>Pseudopanax crassifolius</trans>
  <note>Mac-Thalla VIII (1899) No. 13 100/4: "Thugadh dha bata craobh fheoir (grass tree) New Zealand air a dheanamh sgiamhach le or, le deadh ruin a chomuinn".</note>
</lexeme>
